security:
    encoders:
        SM\UserBundle\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
            main:
                entity:
                    class: SM\UserBundle\Entity\User
                    property: username

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:  /logout
                target:  /

    access_control:
           - { path: ^/secure_area, roles: ROLE_USER }