index:
    pattern: /
    defaults: { _controller: SMUserBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: SMUserBundle:Default:login }

login_check:
    pattern:   /login_check

test_security:
    pattern: /secure_area
    defaults: {_controller: SMUserBundle:Default:secure }

logout:
    path: /logout